### ISSUE TITLE
Svelte update (3.5.1 > 3.5.2) and BOOOM! (problems, not joys)

### ISSUE THREAD

**Issue by frederikhors** [lukeed/navaid#20]
Taking your https://codesandbox.io/s/reverent-tesla-c0kq0 from https://github.com/lukeed/navaid/issues/13.

- If you upgrade to **3.5.1** is ok:

_(one click on "Go to Teams Page")_
![image](https://user-images.githubusercontent.com/41120635/59794435-42ee9000-92d9-11e9-9010-127246dc2d82.png)

- If you upgrade to **3.5.2** is not:

_(one click on "Go to Teams Page")_
![image](https://user-images.githubusercontent.com/41120635/59794468-51d54280-92d9-11e9-81d2-5a496868c2a2.png)

What can it be?

**Comment by frederikhors** [comment]
On one of my projects the error is frightening:

```log
TypeError: Cannot read property '$$' of undefined
```

**Comment by lukeed** [comment]
Don't know. This isn't an issue for here bud.

**Comment by frederikhors** [comment]
You leave me hopeless. I'm sad.

At least with this reproduction and with your experience - in the blink of an eye - we can help the authors understand the problem.

**Comment by lukeed** [comment]
I just ran this. Your problem isn't there. What you're seeing is the long-standing issue of the Codesanbox `iframe` not being properly reset. If your force-reload the page and navigate around, you'll see that the `PageTeamList` only logs once per navigation.

It "grows"/adds a repetition every time you make a change to application without refreshing. This has always been the case and I see it fairly often in codesandbox links w/ routers.

In any event, this isn't a Navaid issue which is why I closed it

**Comment by frederikhors** [comment]
Opened here: https://github.com/sveltejs/svelte/issues/3054

**Comment by frederikhors** [comment]
You cannot navigate anymore as you can see in the second problem.

**Comment by frederikhors** [comment]
Thanks anyway for being as nice as you are.

**Comment by frederikhors** [comment]
Maybe related: https://github.com/sveltejs/svelte/issues/3055
