### ISSUE TITLE
Nested routes wildcard *

### ISSUE THREAD

**Issue by frederikhors** [lukeed/navaid#24]
In the sample project https://codesandbox.io/s/trusting-lamarr-zdmlb `App.svelte` has:

```js
const router = Navaid()
    .on("", () => draw(Home))
    .on("teams", () => draw(Teams))
    .on("teams/*", () => draw(Teams))
    .listen();
```

As you can see I have:

```js
.on("teams", () => draw(Teams))
.on("teams/*", () => draw(Teams))
```

**Is it possible to use just one?** Something like:

```js
.on("teams*", () => draw(Teams))
```

**Comment by lukeed** [comment]
Yes, it is:

```js
const router = Navaid()
    .on("/", () => draw(Home))
    .on("/teams*", () => draw(Teams))
    .listen();
```

You just have to be careful that `/teams` is unique because `/teams*` will also match `/teamship/hello` urls too.

---

There _would be_ a way for Navaid to use RegExp patterns ([like Trouter](https://github.com/lukeed/trouter#pattern)) but then Navaid completely loses the ability to parse parameter segments for you when:

A) You don't create the RegExp correctly
B) You choose not to use named RegExp groups
C) Your browser/runtime doesn't support named RegExp groups

Seemed reason enough not to add it.

---

Hope that helps~

**Comment by frederikhors** [comment]
Oh I see the problem now. If I use something like this:

```js
const router = Navaid()
    .on("/", () => draw(Home))
    .on("/teams*", () => draw(Teams))
    .on('*', () => draw(PageNotFound))
    .listen();
```

it does't work.

How to handle this case?
