### ISSUE TITLE
Allow for state params in pushState

### ISSUE THREAD

**Issue by cdock1029** [lukeed/navaid#6]
Starting to use your library with Svelte 3. This is either a question or feature request...

I see the pushState events are basically using the `state` param for the uri. This removes ability to `history.pushState(someRouteState, ...)` right?

Seems like it would be nice to have pushState `state` param, say, default to null but be available to use.... when caching some route data like here:

https://twitter.com/ryanflorence/status/1111272046372093953

None of the other generic routers seem to handle this well OR they don't handle search params well or something. Yours is best so far and small. But having state available would be nice.

**Comment by lukeed** [comment]
Hey, thank you

I thought about this initially, but it's a _really_ unreliable thing to do. Problem is that if you're not explicitly providing defaults and fallbacks on every single route (or every single time you read history state) then you will have faulty/undefined data.

For example, / to /about to /blog/hello-world

If that's the path you plan for, should be fine. But if user enters your app AT /about or AT any blog post, you'd have to manually define the fallback data you expected to have, or suffer errors.

You basically end up coding the app twice

IMO it's much better to just rely on the URL since that's common to all entry points and all rendering contexts, including server-side.

**Comment by cdock1029** [comment]
Yea I've discovered it is not useful for data that can be encoded in the url which you should then use search params instead.

But it still could be opt in, (if the state was passed through from pushState) and the usage would be for initializing your various api fetchers that will run for a given route.. the initial values in rxjs Behavior subjects or svelte stores for example.

No worries if you don't think its that useful though

**Comment by lukeed** [comment]
Yeah, I haven't found _any_ use personally. I don't think it's worth supporting since it generally leads to confusing and messy rabbit holes.

It sounds like you've spent a fair amount of time playing with it. Would like to see a good practice/pattern if you think you've found one!

Otherwise I'll remain disappointed and don't wanna lead others down that path.

**Comment by lukeed** [comment]
Ah sorry @cdock1029. I drifted off the other night~

Still open to discuss this, but I still don't think `history` state belongs in most SPA setups given the issues above. Sounds like maybe you arrived to same conclusion?

**Comment by cdock1029** [comment]
No worries 👍... I think the canonical example is just a slight
optimization when routing to sub route where you have the data already,
which then it's just the initial state (state || undefined), so not *too*
complex in that case and consistent on refresh.

Other than that, I could see wanting to stay consistent with native API,
but it's not super necessary to have I guess.
